server:
  port: 8085

spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**

        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/ratings/**

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/